function xp = expconstants

xp.TRIG_ONSET_FIXATION = 1;

xp.TRIG_ONSET_CUE_LEFT = 2;
xp.TRIG_ONSET_CUE_RIGHT = 3;

xp.TRIG_ONSET_GRATING_CW_CW = 11;
xp.TRIG_ONSET_GRATING_CW_CCW = 12;
xp.TRIG_ONSET_GRATING_CCW_CW = 13;
xp.TRIG_ONSET_GRATING_CCW_CCW = 14;

xp.TRIG_ONSET_ROTATION_L_CW = 21;
xp.TRIG_ONSET_ROTATION_L_CCW = 22;
xp.TRIG_ONSET_ROTATION_R_CW = 23;
xp.TRIG_ONSET_ROTATION_R_CCW = 24;

xp.TRIG_OFFSET_GRATING = 6;

end
